services:
  db:
    image: postgres:15
    container_name: test-go-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5430:5432'
    volumes:
      - db:/var/lib/postgresql/test-go-db
    networks:
      - test-go-network
  
  authentication:
    image: test-go-authentication
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-go-authentication
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      IP_NOTIFICATION_WEBHOOK: ${IP_NOTIFICATION_WEBHOOK}
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - test-go-network

volumes:
  db:
    driver: local

networks:
  test-go-network:
    driver: bridge